// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/sakura-widget/SakuraWidgetPosition.tsx": () => import("../components/mockups/sakura-widget/SakuraWidgetPosition.tsx")
};
